services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: open/infra/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/postgres
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
