name: Agent
on:
  push:
  pull_request:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "17 * * * *"
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: '3.13' }
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r open/requirements.txt -r open/requirements-dev.txt
      - name: Unit tests
        run: pytest -q open/api/test_api.py
      - name: Integration tests (soft-fail)
        continue-on-error: true
        run: pytest -q open/api/test_integration.py
      - name: Docker build
        run: docker build -f open/infra/Dockerfile -t api:ci .
      - name: Docker smoke
        run: |
          docker run -d -p 8000:8000 --name api api:ci
          for i in {1..30}; do curl -sf http://127.0.0.1:8000/health && break || sleep 1; done
          curl -sf http://127.0.0.1:8000/health
      - name: Tear down
        if: always()
        run: docker rm -f api || true

  autofix:
    runs-on: ubuntu-latest
    needs: ci
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: '3.13' }
      - name: Run auto-format/lint
        run: bash scripts/format_lint.sh
      - name: Create PR with changes (if any)
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(agent): auto-format & lint"
          title: "Agent: auto-format & lint"
          body: "Automated changes by Agent."
          branch: agent/autofix
          labels: agent, autofix
