name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r open/requirements.txt -r open/requirements-dev.txt
      - name: Unit tests
        run: pytest -q open/api/test_api.py
      - name: Integration tests (soft-fail)
        continue-on-error: true
        run: pytest -q open/api/test_integration.py
  docker-build:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Build API image
        run: docker build -f open/infra/Dockerfile -t api:ci .
      - name: Smoke run
        run: |
          docker run -d -p 8000:8000 --name api api:ci
          for i in {1..20}; do
            curl -sf http://127.0.0.1:8000/health && break || sleep 1; done
          curl -sf http://127.0.0.1:8000/health
      - name: Tear down
        if: always()
        run: docker rm -f api || true
